### ISSUE TITLE
Sending to Kodi has no effect

### ISSUE THREAD

**Issue by eNBeWe** [dirkjanm/firefox-send-to-xbmc#15] opened 2015-03-27 17:34 UTC
Hi,

I believe it is now the fourth try to get this plugin working.
When I try to send some content to my Media Center nothing happens.

I am using Send to XBMC 2.2.0 with  Firefox 36 under Ubuntu 14.04 x64.
The Kodi is 14.2 running under OpenElec 5.0.6. on a Raspberry Pi.

The Web interface is reachable with the correct credentials. The same interface is used by my Yatse Remote on Android and working fine. I configured the media center in the configuration interface and it shows up in the context menu.
Yet all I get when I try to send a video or music to Kodi is a notification box (Sending to Kodi).
Is there some way of console or debug mode so I can get more info why this is happening?

**Comment by PanderMusubi** [comment] 2015-04-03 19:26
Same for Firefox 37 on Ubuntu 14.10 with Kodi 2:14.1-1~wheezy on Raspberry Pi 2 to which I can play YouTube urls from my smartphone via Yatse.

Please let me know which logging I need to do in order to get this fixed.

**Comment by fleixi** [comment] 2015-05-01 11:17
Same here for Firefox 37 on Kubuntu 15.04 with Kodi 14.2 running on Fedora21

Yaste and Webpage of Kodi is working.

**Comment by gammy** [comment] 2015-05-02 11:15
Bump on 36.0.1 on Archlinux (versions vary), Kodi 14.2.

**Comment by eNBeWe** [comment] 2015-05-06 22:09
I managed to get it working through a bit of debugging and poking around.
It seems to be either a problem with the port or the password. This is resulting in a malformed URL which is rejected by the addon-infrastructure.
I changed the webinterface of my Kodi to port 80 and removed all special characters from the password.

**Comment by dirkjanm** [comment] 2015-05-08 07:48
Nice find, I'm going to have to test it with special characters in the password. Its possible they aren't escaped properly when sending the url to Kodi.

**Comment by fleixi** [comment] 2015-05-09 13:22
There are no special characters in my password but im running the webinterface on an other port than 80.

**Comment by dirkjanm** [comment] 2015-05-10 11:29
I've been trying to reproduce this on a clean install of Ubuntu Desktop 14.04 as a VM with both Kodi 15.0 beta running on Windows and Kodi 14 running on a raspberry Pi. Tried both Firefox 35 and Firefox 37. I could not reproduce the issue.

I did find an issue with the escaping of usernames/passwords in the plugin which could cause some problems for passwords with special characters (however for some reason it never gave problems in my tests). The escaping will be fixed in the next version.

The only time that the plugin didn't do anything after the "Sending to Kodi..." was when an invalid hostname was used. For some reason Firefox never completes the request in this case. If you're having problems with the plugin doing nothing, please enter the IP address instead of the hostname. To test if Firefox works with the hostname, enter http://yourhostname:port in your browser. If it times out, it will not work in the plugin either.

Let me know if the above solves your problems.

**Comment by eNBeWe** [comment] 2015-05-10 20:58
Okay, I changed the port back top 8080 and it still works. So I'm assuming it was a Problem with the password. I had lots of things like %~+#§* in the password, so if anything could break it ... I would manage to do it.

**Comment by dirkjanm** [comment] 2015-05-10 21:09
The issue with the passwords should be solved in a60372ce2de4472b3cecea61d032c0de779091e7

**Comment by fleixi** [comment] 2015-05-14 09:08
Is working again by me too. I think the bug is fixed

**Comment by PanderMusubi** [comment] 2015-05-30 21:55
Same here. On Firefox 38 on Ubuntu 15.04 it works.

**Closed** 2015-08-15 20:38 UTC
Labels: bug
