### ISSUE TITLE
Preferences keep being lost

### ISSUE THREAD

**Issue by Morgyn** [dirkjanm/firefox-send-to-xbmc#55] opened 2017-05-30 12:17 UTC
Every so often on all my browsers, my sendtokodi preferences are lost, meaning I have to reconfigure.

This is really irritating.

**Comment by dirkjanm** [comment] 2017-06-05 18:00
I understand that it is really irritating that settings get lost. However the chance that this is caused by the plugin is very minimal, the plugin just uses the APIs provided by Mozilla, and does not do anything with complex settings. Most likely it is related to your firefox profile. Are you using sync? That would explain why the addon loses its data on all your computers.
Another discussion about lost preferences was in #2, in the end it also turned out to be browser related.
Unless there is some evidence that the plugin is causing this, I will have to close this issue since it seems to only affect a few people.

**Closed by dirkjanm** 2017-06-05 18:00 UTC
