### ISSUE TITLE
DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=ID"

### ISSUE THREAD

**Issue by llucax** [dirkjanm/firefox-send-to-xbmc#39] opened 2016-03-08 01:54 UTC
Kodi logs say:
```
22:43:43 T:139889794426624 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=ID"
22:43:43 T:139889794426624 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=ID"
```

And the plugin docs says something different (http://kodi.wiki/view/Add-on:YouTube).

**Comment by dirkjanm** [comment] 2016-03-08 19:53
This is still on the todo list, duplicate of #29

**Closed by dirkjanm** 2016-03-08 19:53 UTC
